name: Basic Variables
on:
  workflow_dispatch

env:
  MY_NAME: Mohamed Hashim

jobs:
  print-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Basic Variables
        run:  echo ${{vars.MY_CONFIG_VAR}}
